# Generated by Django 5.2.7 on 2025-11-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=100)),
                ('descripcion_evento', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'evento_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoRangoEdad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'evento_rango_edad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id_logro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_logro', models.CharField(max_length=50)),
                ('descripcion_logro', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Palmares',
            fields=[
                ('id_palmares', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'palmares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('url_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'perfil_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('comentarios_logro', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil_logro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangoEdad',
            fields=[
                ('id_rango_edad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rango_edad', models.CharField(max_length=40)),
                ('edad_minima', models.IntegerField(blank=True, null=True)),
                ('edad_maxima', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rango_edad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('estado_resultado', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'resultado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
    ]
