# Generated by Django 5.2.7 on 2025-11-13 16:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=100)),
                ('descripcion_evento', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id_logro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_logro', models.CharField(max_length=50)),
                ('descripcion_logro', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RangoEdad',
            fields=[
                ('id_rango_edad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rango_edad', models.CharField(max_length=40)),
                ('edad_minima', models.IntegerField(blank=True, null=True)),
                ('edad_maxima', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rango_edad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('estado_resultado', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'resultado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='perfil_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='perfil_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('id_rol', models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.rol')),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Palmares',
            fields=[
                ('id_palmares', models.AutoField(primary_key=True, serialize=False)),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_resultado', models.ForeignKey(db_column='id_resultado', on_delete=django.db.models.deletion.CASCADE, to='api.resultado')),
            ],
            options={
                'db_table': 'palmares',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
            ],
            options={
                'db_table': 'evento_categoria',
                'managed': True,
                'unique_together': {('id_evento', 'id_categoria')},
            },
        ),
        migrations.CreateModel(
            name='PerfilLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('comentarios_logro', models.TextField(blank=True, null=True)),
                ('id_logro', models.ForeignKey(db_column='id_logro', on_delete=django.db.models.deletion.CASCADE, to='api.logro')),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_logro',
                'managed': True,
                'unique_together': {('id_perfil', 'id_logro')},
            },
        ),
        migrations.CreateModel(
            name='EventoRangoEdad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('id_rango_edad', models.ForeignKey(db_column='id_rango_edad', on_delete=django.db.models.deletion.CASCADE, to='api.rangoedad')),
            ],
            options={
                'db_table': 'evento_rango_edad',
                'managed': True,
                'unique_together': {('id_evento', 'id_rango_edad')},
            },
        ),
        migrations.CreateModel(
            name='PerfilEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.RESTRICT, to='api.estado')),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.RESTRICT, to='api.rol')),
            ],
            options={
                'db_table': 'perfil_evento',
                'managed': True,
                'unique_together': {('id_perfil', 'id_evento')},
            },
        ),
    ]
