# Generated by Django 5.2.7 on 2025-12-13 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_populate_resultados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilevento',
            name='id_rol',
            field=models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.rol'),
        ),
    ]
